---
blank_issues_enabled: false
contact_links:
  - name: SocialEyes Community Support
    url: https://github.com/beatlab-mcmaster/SocialEyes/discussions
    about: Please ask and answer questions here.
